import { TOKENS } from './tokens';

const VLX = TOKENS[0];

export const marketOrders = [
  {
    id: 'ORD-78421',
    seller: 'NeoDesk',
    token: VLX,
    quantity: 120,
    amount: 9000,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 98,
    trades: 1240,
    payTime: 10,
    minLimit: 1500,
    maxLimit: 9000,
  },
  {
    id: 'ORD-78424',
    seller: 'QuickPay',
    token: VLX,
    quantity: 40,
    amount: 3000,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 97,
    trades: 410,
    payTime: 8,
    minLimit: 1000,
    maxLimit: 3000,
  },
  {
    id: 'ORD-78425',
    seller: 'NovaSettle',
    token: VLX,
    quantity: 75,
    amount: 5625,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 95,
    trades: 622,
    payTime: 10,
    minLimit: 1500,
    maxLimit: 5625,
  },
  {
    id: 'ORD-78422',
    seller: 'BlueMint',
    token: VLX,
    quantity: 250,
    amount: 18750,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 96,
    trades: 842,
    payTime: 15,
    minLimit: 2500,
    maxLimit: 18750,
  },
  {
    id: 'ORD-78426',
    seller: 'MintDesk',
    token: VLX,
    quantity: 180,
    amount: 13500,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 98,
    trades: 955,
    payTime: 14,
    minLimit: 2000,
    maxLimit: 13500,
  },
  {
    id: 'ORD-78427',
    seller: 'RupeeFlow',
    token: VLX,
    quantity: 320,
    amount: 24000,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 96,
    trades: 1188,
    payTime: 12,
    minLimit: 4000,
    maxLimit: 24000,
  },
  {
    id: 'ORD-78423',
    seller: 'Alpha INR',
    token: VLX,
    quantity: 500,
    amount: 37500,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 99,
    trades: 2106,
    payTime: 12,
    minLimit: 5000,
    maxLimit: 37500,
  },
  {
    id: 'ORD-78428',
    seller: 'PrimeINR',
    token: VLX,
    quantity: 650,
    amount: 48750,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 99,
    trades: 3020,
    payTime: 15,
    minLimit: 7500,
    maxLimit: 48750,
  },
  {
    id: 'ORD-78429',
    seller: 'SettleX',
    token: VLX,
    quantity: 900,
    amount: 67500,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 94,
    trades: 774,
    payTime: 18,
    minLimit: 10000,
    maxLimit: 67500,
  },
  {
    id: 'ORD-78430',
    seller: 'VaultTrade',
    token: VLX,
    quantity: 1200,
    amount: 90000,
    rewardAmount: 15,
    status: 'verified pending',
    completion: 99,
    trades: 4211,
    payTime: 20,
    minLimit: 15000,
    maxLimit: 90000,
  },
];

export const userOrders = [
  {
    id: 'BUY-91024',
    transactionId: 'TXN-101',
    type: 'buy',
    token: VLX,
    quantity: 250,
    amount: 18750,
    status: 'completed',
    counterparty: 'BlueMint',
    date: '10 May 2026',
    expiresIn: 'Completed',
    expiryProgress: 100,
  },
  {
    id: 'SELL-62018',
    transactionId: 'TXN-102',
    type: 'sell',
    token: VLX,
    quantity: 500,
    amount: 37500,
    status: 'awaiting payment',
    counterparty: 'Awaiting buyer',
    date: '09 May 2026',
    expiresIn: '42 min remaining',
    expiryProgress: 70,
  },
  {
    id: 'BUY-88412',
    transactionId: 'TXN-097',
    type: 'buy',
    token: VLX,
    quantity: 120,
    amount: 9000,
    status: 'processing',
    counterparty: 'NeoDesk',
    date: '08 May 2026',
    expiresIn: '18 min remaining',
    expiryProgress: 30,
  },
  {
    id: 'BUY-55210',
    transactionId: 'TXN-109',
    type: 'buy',
    token: VLX,
    quantity: 80,
    amount: 6000,
    status: 'awaiting payment',
    counterparty: 'QuickPay',
    date: '10 May 2026',
    expiresIn: '10 min remaining',
    expiryProgress: 84,
    payTime: 10,
  },
  {
    id: 'SELL-44780',
    transactionId: 'TXN-110',
    type: 'sell',
    token: VLX,
    quantity: 160,
    amount: 12000,
    status: 'processing',
    counterparty: 'M3 Wallet verification',
    date: '10 May 2026',
    expiresIn: '3 min remaining',
    expiryProgress: 68,
    verifyMinutes: 3,
  },
  {
    id: 'BUY-33742',
    transactionId: 'TXN-111',
    type: 'buy',
    token: VLX,
    quantity: 60,
    amount: 4500,
    status: 'under review',
    counterparty: 'NovaSettle',
    date: '10 May 2026',
    expiresIn: 'Under review',
    expiryProgress: 52,
  },
  {
    id: 'SELL-75802',
    transactionId: 'TXN-112',
    type: 'sell',
    token: VLX,
    quantity: 90,
    amount: 6750,
    status: 'cancelled',
    counterparty: 'Buyer timeout',
    date: '09 May 2026',
    expiresIn: 'Cancelled',
    expiryProgress: 0,
  },
  {
    id: 'SELL-90418',
    transactionId: 'TXN-113',
    type: 'sell',
    token: VLX,
    quantity: 210,
    amount: 15750,
    status: 'completed',
    counterparty: 'PrimeINR',
    date: '08 May 2026',
    expiresIn: 'Completed',
    expiryProgress: 100,
  },
];

export const activities = [
  'Bought 250 VLX through M3 Wallet settlement',
  'Reward credited for VLX Token order',
  'Referral rebate received from L1 user',
  'Coupon FT-BOOST is active for Fast Track',
];

export const coupons = [
  { code: 'FT-BOOST', title: 'Fast Track Fee Saver', expiry: '2026-06-14', status: 'active' },
  { code: 'REWARDX', title: 'Reward Booster', expiry: '2026-05-28', status: 'active' },
  { code: 'NEWVLX', title: 'New Trader Bonus', expiry: '2026-04-19', status: 'expired' },
];

export const historyRows = [
  { id: 'TXN-101', type: 'Buy', token: 'VLX', amount: 'INR 18,750', status: 'completed', date: '10 May 2026' },
  { id: 'TXN-102', type: 'Sell', token: 'VLX', amount: 'INR 37,500', status: 'pending', date: '09 May 2026' },
  { id: 'TXN-103', type: 'Reward', token: 'VLX', amount: 'INR 450', status: 'completed', date: '08 May 2026' },
  { id: 'TXN-104', type: 'Referral', token: '-', amount: 'INR 440', status: 'completed', date: '07 May 2026' },
];

export const notifications = [
  { title: 'Payment verification pending', body: 'Submit the M3 Wallet transaction ID before timer expiry.', type: 'wallet' },
  { title: 'Reward credited', body: 'VLX reward of INR 15 was added to your wallet ledger.', type: 'reward' },
  { title: 'Coupon expiring soon', body: 'FT-BOOST expires in 35 days.', type: 'coupon' },
  { title: 'Referral rebate received', body: 'L2 activity generated a new rebate.', type: 'referral' },
];

export const supportTickets = [
  {
    id: 'TKT-10091',
    subject: 'Payment verification pending',
    category: 'Payment',
    priority: 'High',
    status: 'open',
    createdAt: '10 May 2026',
    lastUpdate: '12 min ago',
    messages: [
      { by: 'user', body: 'I submitted my M3 Wallet transaction ID but the order is still pending.', at: '10:10 AM' },
      { by: 'support', body: 'We are checking the payment reference and screenshot. Please wait for confirmation.', at: '10:18 AM' },
    ],
  },
  {
    id: 'TKT-10064',
    subject: 'VLX sell order reward',
    category: 'Rewards',
    priority: 'Medium',
    status: 'in_review',
    createdAt: '09 May 2026',
    lastUpdate: '1 hr ago',
    messages: [
      { by: 'user', body: 'My manual sell order reward is not visible.', at: '09:30 AM' },
      { by: 'support', body: 'Reward will reflect after final settlement is marked completed.', at: '09:44 AM' },
    ],
  },
  {
    id: 'TKT-10012',
    subject: 'Wallet OTP not received',
    category: 'Wallet',
    priority: 'Low',
    status: 'resolved',
    createdAt: '07 May 2026',
    lastUpdate: '2 days ago',
    messages: [
      { by: 'user', body: 'Wallet OTP was delayed.', at: '02:12 PM' },
      { by: 'support', body: 'OTP delivery issue has been resolved. Please retry wallet verification.', at: '02:30 PM' },
    ],
  },
];
